USE WAREHOUSE WH_INGEST;
USE DATABASE SEC_PRICING;
USE SCHEMA DM_DIM;

MERGE INTO DM_DIM.DIM_SECURITY d
USING (
  SELECT DISTINCT
    UPPER(TRIM(SYMBOL)) AS SYMBOL
  FROM CORE.EOD_PRICES
  WHERE TRADE_DATE = TO_DATE('{{ ti.xcom_pull(task_ids='validate_metadata')["trading_date"] }}')
) s
ON d.SYMBOL = s.SYMBOL
WHEN NOT MATCHED THEN INSERT (SYMBOL)
VALUES (s.SYMBOL);
