USE WAREHOUSE WH_INGEST;
USE DATABASE SEC_PRICING;
USE SCHEMA DM_DIM;

MERGE INTO DM_DIM.DIM_DATE d
USING (
  SELECT DISTINCT
    TO_NUMBER(TO_CHAR(TRADE_DATE, 'YYYYMMDD')) AS DATE_SK,
    TRADE_DATE AS CAL_DATE,
    YEAR(TRADE_DATE) AS YEAR_NUM,
    QUARTER(TRADE_DATE) AS QUARTER_NUM,
    MONTH(TRADE_DATE) AS MONTH_NUM,
    MONTHNAME(TRADE_DATE) AS MONTH_NAME,
    DAY(TRADE_DATE) AS DAY_NUM,
    DAYNAME(TRADE_DATE) AS DAY_NAME,
    DAYOFWEEK(TRADE_DATE) AS DAY_OF_WEEK,
    WEEK(TRADE_DATE) AS WEEK_OF_YEAR,
    DAYOFWEEK(TRADE_DATE) IN (0,6) AS IS_WEEKEND
  FROM CORE.EOD_PRICES
  WHERE TRADE_DATE = TO_DATE('{{ ti.xcom_pull(task_ids='validate_metadata')["trading_date"] }}')
) s
ON d.DATE_SK = s.DATE_SK
WHEN NOT MATCHED THEN INSERT (
  DATE_SK, CAL_DATE, YEAR_NUM, QUARTER_NUM, MONTH_NUM,
  MONTH_NAME, DAY_NUM, DAY_NAME, DAY_OF_WEEK,
  WEEK_OF_YEAR, IS_WEEKEND
)
VALUES (
  s.DATE_SK, s.CAL_DATE, s.YEAR_NUM, s.QUARTER_NUM,
  s.MONTH_NUM, s.MONTH_NAME, s.DAY_NUM, s.DAY_NAME,
  s.DAY_OF_WEEK, s.WEEK_OF_YEAR, s.IS_WEEKEND
);
