USE WAREHOUSE WH_INGEST;
USE DATABASE SEC_PRICING;
USE SCHEMA CORE;

MERGE INTO CORE.EOD_PRICES tgt
USING (
  SELECT
    TRADE_DATE,
    UPPER(TRIM(SYMBOL)) AS SYMBOL,
    OPEN, HIGH, LOW, CLOSE, VOLUME
  FROM RAW.RAW_EOD_PRICES
  WHERE TRADE_DATE = TO_DATE('{{ ti.xcom_pull(task_ids='validate_metadata')["trading_date"] }}')
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY UPPER(TRIM(SYMBOL)), TRADE_DATE
    ORDER BY _INGEST_TS DESC, _SRC_FILE DESC
  ) = 1
) src
ON tgt.SYMBOL = src.SYMBOL
AND tgt.TRADE_DATE = src.TRADE_DATE
WHEN MATCHED THEN UPDATE SET
  OPEN   = src.OPEN,
  HIGH   = src.HIGH,
  LOW    = src.LOW,
  CLOSE  = src.CLOSE,
  VOLUME = src.VOLUME,
  LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  TRADE_DATE, SYMBOL, OPEN, HIGH, LOW, CLOSE, VOLUME, LOAD_TS
)
VALUES (
  src.TRADE_DATE, src.SYMBOL, src.OPEN, src.HIGH, src.LOW,
  src.CLOSE, src.VOLUME, CURRENT_TIMESTAMP()
);
